### ISSUE TITLE
Catch_up States

### ISSUE THREAD

**Issue by eddiezab** [Koed00/django-q#110]
I would like to see the option to catch up from missed tasks to 3 states instead of 2. The states would be:

None: Same effect as current boolean False
Once: Instead of all missed occurrences, this just executes the missed task(s) one time.
All: Same effect as current boolean True

**Comment by Koed00** [comment]
The current behavior for `catch_up: False` is to execute the missed task and then set the next schedule past the current date instead of in the past. Which is what you describe as 'once', since it's impossible to have multiple missed schedules of the same task. Maybe this is not entirely clear from the documentation.
.

**Comment by eddiezab** [comment]
Thanks for the clarification. I think what threw me off was this statement:

> Any hourly schedules you had will run 24 times, once every schedule loop, until they are back in sync

found in the Missed schedules section  of this page: https://django-q.readthedocs.org/en/latest/schedules.html

**Comment by Koed00** [comment]
Some of it I wrote in a hurry ;) I'll see if I can make it a little clearer.

What happens in the code by default is this:

* find a task with a scheduled time in the past
* run it
* add the schedule type to original scheduled time ( i.e. 1 hour or 1 day etc)
* save the new scheduled time

So if the schedule was 24 hours behind, it will be rescheduled to 23 hours behind.
Which effectively runs immediately, since it's in the past too. This keeps happening until the scheduled time is in the future.

Setting `catch_up`  to False, modifies the save step to loop back to the add 1 hour (or 1 day etc) until the new scheduled time is in the future before it saves it.

This way you always preserve the original run time, day of the week etc of the schedule.

**Comment by Koed00** [comment]
Does #112 make it a little clearer?

**Comment by eddiezab** [comment]
I think so. Thank you a again for the clarification! I'm looking forward to
integrating this with my project.
